### ISSUE TITLE
REST Client does not actually use client permissions

### ISSUE THREAD

**Issue by seii** [hazelcast/imdg-docs#113]
In the section [Native Client Security](https://docs.hazelcast.com/imdg/latest/security/native-client-security.html#authentication), a generic structure is defined for setting up security realms and permissions for data structures. However, the [REST Client](https://docs.hazelcast.com/imdg/latest/clients/rest.html) does not actually respect any defined permissions.

We should definitely have either an INFO or a WARNING-level text box in the REST Client section so that users do not attempt to set permissions which would not actually be enforced.

**Comment by Serdaro** [comment]
Also added a more comprehensive Security content for the REST API here: https://github.com/hazelcast/hz-docs/pull/267
