### ISSUE TITLE
Issues with querying chapter

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/imdg-docs#120]
There are a few issues with this chapter.

This section https://docs.hazelcast.com/imdg/latest/query/how-distributed-query-works.html#querying-with-sql should probably not be named "Querying with SQL" since it's not SQL and we now have "real" SQL query engine. They should also probably be linked together.

Additionally, this note is no longer true, cc @petrpleshachkov :
```
JSON metadata is stored on-heap even when you use the NATIVE in-memory format. If you are storing HazelcastJsonValues in your NATIVE maps, there is a certain amount of on-heap cost per object. Metadata is not created unless you put HazelcastJsonValues in your NATIVE maps even when metadata creation is on. 
```

**Comment by Serdaro** [comment]
@Holmistr , a note with link to the SQL chapter was added for the master branch: https://github.com/hazelcast/imdg-docs/commit/8177d1fc7440a9bcbc7651cb1f93a09b78eabae0.

I am thinking of changing the title of the section in question to "Querying with SQL-like Predicates".

And the note about JSON metadata (https://github.com/hazelcast/hazelcast/pull/18186); yes, not valid anymore I suppose.
