### ISSUE TITLE
Docs: Feedback for Metrics - Include complete list of metrics with descriptions

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/imdg-docs#131]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.1.1/docs/modules/management/pages/metrics.adoc)

It would be nice to have a comprehensive list of all the metrics along with a short description of each. Currently, the closest thing is [JMX API per Member](https://docs.hazelcast.com/imdg/latest/management/jmx-api.html), but this doesn't have the descriptions, and it's not clear if these apply to all metrics consumers (not just JMX).

**Comment by Serdaro** [comment]
@sumnerib , there is an effort in progress for the matter in question. You can track it at https://github.com/hazelcast/imdg-docs/pull/121

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/108
