### ISSUE TITLE
Change the nesting of Installing/Upgrading and Running

### ISSUE THREAD

**Issue by nfrankel** [hazelcast/imdg-docs#144]
From https://hazelcast.slack.com/archives/C035HQET5/p1616053791003400

i’d suggest to change the nesting level:

* top level: cli, archives, docker, cloud kubernetes, cloud providers
* put tanzu under cloud providers
* put modular java and supported jvm archives -> there’s no need to dive into that if i’m running docker or cli that come with their own jvm

also, the section about launching is very coupled to how you install in the first place
https://docs.hazelcast.com/imdg/latest/starting-members-clients.html

**Comment by Serdaro** [comment]
I think the outline in the 5.0 documentation is more clear now. Please feel free to reopen it with comments out of the new documentation in the new repo (hazelcast/hz-docs).
