### ISSUE TITLE
Improving the documentation on Serialization

### ISSUE THREAD

**Issue by nfrankel** [hazelcast/imdg-docs#145]
I had a couple of interactions about how serialization works:

* https://hazelcast.slack.com/archives/C034YQBTG/p1616084349025500
* https://hazelcast.slack.com/archives/C035HQET5/p1616087416008600

Now I understand that serialization is done client-side. I think that should be made more obvious in the documentation:

* The section on [clients](https://docs.hazelcast.com/imdg/latest/clients/hazelcast-clients.html) doesn't mention serialization
* It's mentioned in the [Java client](https://docs.hazelcast.com/imdg/latest/clients/java.html#client-serialization-configuration) but in no other clients
* It should probably be moved at the root clients level
* It should definitely be a bit developed
* The [section on serialization](https://docs.hazelcast.com/imdg/latest/serialization/serialization.html) mentions that serialization is required to move data from member to member, but nothing about client-server

Nitpick in the above section, there's redundancy:

> Hazelcast optimizes the serialization for the basic types and their array types. You cannot override this behavior.

And a couple of lines later:

> Hazelcast optimizes all of the above object types. You do not need to worry about their (de)serializations.

**Comment by JakeSCahill** [comment]
Thanks @nfrankel 👌 Just so I'm clear from the conversations. Are the two use cases:
- **Registering a serializer on members:** Allows members to store keys/values in-memory as objects, use them in entry processing as well as index and query them.
- **Serializing on the client side:** Allows clients to simply store keys/values as binary and handle deserialization themselves. 

The missing docs being the client-side serialization.

Does client-side serialization stop members from being able to access keys/values for entry processing/indexing/querying?

**Comment by sancar** [comment]
> Does client-side serialization stop members from being able to access keys/values for entry processing/indexing/querying?

No, they are orthogonal. One can use both of them at the same time.

**Comment by JakeSCahill** [comment]
I mean if you only use client-side serialisation, in which case the member would only be aware of the binary data.

**Comment by JakeSCahill** [comment]
After speaking with @sancar, we can also document the following scenarios where you *would* need to configure serialization on the member side (in client/server topologies):
- When the data structure's values are stored as objects
- When you want to process map entries (except when using the Java client with `Portable` serialization in version 4.1 or greater)
- When you use SQL queries on nested fields whose values are not primitives

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/109
