### ISSUE TITLE
Docs: Feedback for Database CDC Integration using Striim Hot Cache

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/imdg-docs#146]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.1.2/docs/modules/ROOT/pages/striim-cdc.adoc)

This feature is not supported in 4.x versions of Hazelcast and you don't find this out until half way down the page.

We should either:
- Completely exclude this content from 4.x versions (probably preferred)
- Bring the information about support versions closer to the beginning of the page

We might also consider a standard way of presenting restrictions in specific versions, for example a custom callout.

**Comment by Serdaro** [comment]
Fixed with the above commits
