### ISSUE TITLE
Docs: Feedback for Monitoring with JMX

### ISSUE THREAD

**Issue by Atchaya-Sundaramoorthy** [hazelcast/imdg-docs#147]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.1.2/docs/modules/management/pages/jmx-monitoring.adoc)

Where to add the -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 ... I couldnt understand where to exactly add these lines   Please help with this

**Comment by Serdaro** [comment]
Hello @Atchaya-Sundaramoorthy , you can set these properties on your command line, e.g.,:

```
java -Dcom.sun.management.jmxremote.port=1099
```

**Comment by Atchaya-Sundaramoorthy** [comment]
Hi @Serdaro ... for setting these properties do we need hazelcast command line ? I need to connect it to the remote process with the use of jmx.  Will it work ?

**Comment by Serdaro** [comment]
@Atchaya-Sundaramoorthy , I don't think you need a Hazelcast command line since those Java specific properties.

**Comment by Atchaya-Sundaramoorthy** [comment]
@Serdaro  can u give me step by step proceedure. Coz i tried the above argument but i couldnt get anything in the remote process of jconsole

what exactly do we need to give in the command line?

**Comment by Atchaya-Sundaramoorthy** [comment]
Kindly send me the step by step process.  I am novice in it and i couldnt get any data in the remote process

**Comment by Serdaro** [comment]
It should be like this:

1 - Run the first two Java specific properties:

```
java -Dcom.sun.management.jmxremote
java -Dcom.sun.management.jmxremote.port=1099
```

2 - Enable the JMX in Hazelcast XML or YAML configuration: 

Example XML:

```
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.jmx">true</property>
    </properties>
    ...
</hazelcast>
```

**Comment by Atchaya-Sundaramoorthy** [comment]
while running the java specific properties i am getting some errors sir . like it just suggesting me to execute some of the java commands .  Then when i tried to make it in remote process, still i am getting connection refused sir
@Serdaro

**Comment by Atchaya-Sundaramoorthy** [comment]
Can u please help me with this @Serdaro

**Comment by Serdaro** [comment]
@Atchaya-Sundaramoorthy ,

Could you please provide the following information?:

1 - Your operating system
2 - Whether you installed Hazelcast and it is on your classpath

**Comment by Atchaya-Sundaramoorthy** [comment]
1. Ubuntu 20.04 LTS
2. Yes I installed it and it is in my classpath

**Comment by Atchaya-Sundaramoorthy** [comment]
@Serdaro Now i am getting the error like password file read access must be restricted

**Comment by ilkerkorkut** [comment]
@Atchaya-Sundaramoorthy 

I think, there is misinformation in our documentation and it may cause a confusion. 

By default `com.sun.management.jmxremote.ssl` and `com.sun.management.jmxremote.authenticate` properties are `true` by default. You should set these properties as `false`, if you don't want to SSL connection and password security.

```
-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
```
Now, you can connect the service via jconsole remote option.

https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html in that URL you can see the default values for JDK 8.

> Now i am getting the error like password file read access must be restricted

This is normal because of `com.sun.management.jmxremote.authenticate` property was true by default. If you want to enable authenticate you can create a `jmxremote.password` file for your java application(for the same user that runs the application) and you can give the additional parameter 
as `-Dcom.sun.management.jmxremote.password.file=/path/of/the/file/jmxremote.password`

**Comment by Atchaya-Sundaramoorthy** [comment]
Even after setting the authenticate as false i am getting the same issue @Serdaro

**Comment by ilkerkorkut** [comment]
> Even after setting the authenticate as false i am getting the same issue @Serdaro

@Atchaya-Sundaramoorthy Did you set `-Dcom.sun.management.jmxremote.ssl=false` as well?

**Comment by Atchaya-Sundaramoorthy** [comment]
yes @Ser

> 
> 
> > Even after setting the authenticate as false i am getting the same issue @Serdaro
> 
> @Atchaya-Sundaramoorthy Did you set `-Dcom.sun.management.jmxremote.ssl=false` as well?

yes @ilkerkorkut

**Comment by ilkerkorkut** [comment]
> yes @ser
> 
> > > Even after setting the authenticate as false i am getting the same issue @Serdaro
> > 
> > 
> > @Atchaya-Sundaramoorthy Did you set `-Dcom.sun.management.jmxremote.ssl=false` as well?
> 
> yes @ilkerkorkut

@Atchaya-Sundaramoorthy May you please share the latest error you got? (output of the error logs or screenshot would be fine.)

**Comment by Atchaya-Sundaramoorthy** [comment]
![password errorr](https://user-images.githubusercontent.com/66689954/112152813-b2a95180-8c08-11eb-9fe7-a36ee28cbbca.PNG)

**Comment by ilkerkorkut** [comment]
@Atchaya-Sundaramoorthy May you please copy and share the whole run command for hazelcast? It seems there are some missing properties on your command.

For example, you can set the `JAVA_OPTS` as follows right before the running hazelcast;

```
export JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authentication=false -Dcom.sun.management.jmxremote.ssl=false"

# and then you can run the hazelcast start script inside the $HAZELCAST_HOME/bin folder

./start.sh
```

**Comment by Atchaya-Sundaramoorthy** [comment]
> 
> 
> ![password errorr](https://user-images.githubusercontent.com/66689954/112152813-b2a95180-8c08-11eb-9fe7-a36ee28cbbca.PNG)

@ilkerkorkut  At first when i run this i got the error like Password file must be read restricted.  Then i made the command chmod 600 jmxremote.password for the password file .  Then it shows the error like password file is not readable

**Comment by Atchaya-Sundaramoorthy** [comment]
> 
> 
> @Atchaya-Sundaramoorthy May you please copy and share the whole run command for hazelcast? It seems there are some missing properties on your command.
> 
> For example, you can set the `JAVA_OPTS` as follows right before the running hazelcast;
> 
> ```
> export JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authentication=false -Dcom.sun.management.jmxremote.ssl=false"
> 
> # and then you can run the hazelcast start script inside the $HAZELCAST_HOME/bin folder
> 
> ./start.sh
> ```

where should i set this sir.  In start.sh script file ? or in the command line ?

**Comment by ilkerkorkut** [comment]
> > @Atchaya-Sundaramoorthy May you please copy and share the whole run command for hazelcast? It seems there are some missing properties on your command.
> > For example, you can set the `JAVA_OPTS` as follows right before the running hazelcast;
> > ```
> > export JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authentication=false -Dcom.sun.management.jmxremote.ssl=false"
> > 
> > # and then you can run the hazelcast start script inside the $HAZELCAST_HOME/bin folder
> > 
> > ./start.sh
> > ```
> 
> where should i set this sir. In start.sh script file ? or in the command line ?

@Atchaya-Sundaramoorthy You can set it in the command-line.

**Comment by Atchaya-Sundaramoorthy** [comment]
Thank you @ilkerkorkut  and @Serdaro  for the help i got the required result.
