### ISSUE TITLE
Docs: Feedback for Map section Broken links

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/imdg-docs#158]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v3.12.12/docs/modules/data-structures/pages/map.adoc)
 All of the interface links I clicked are broken, we probably need to check the similar ones.

Example: Links in the sentence "To do this, you can use Hazelcast’s MapStore and MapLoader interfaces." https://docs.hazelcast.com/imdg/3.12.12/data-structures/map.html#loading-and-storing-persistent-data

**Comment by Serdaro** [comment]
Fixed and uploaded the docs.
