### ISSUE TITLE
DOCS: IMDG Reference Manual: Minor improvement propositions for intro page - Partners chapter

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/imdg-docs#168]
https://github.com/hazelcast/imdg-docs/blob/master/docs/modules/ROOT/pages/index.adoc

1. Hazelcast partners with leading -> verb “partners” clashes with noun “partners”. I would recommend to change to, say, “Hazelcast partners (noun) offer …” or “Hazelcast collaborates with..”
2. See the Partners page for the full list of and information on our partners. - > We are talking about list of existing partners, but link leads to partners page, not to partners list. I would suggest to change the link to https://hazelcast.com/partners/find-a-partner/ for better user experience
3. See the Partners page for the full list of and information on our partners. - > I don’t feel fully comfortable with this sentence, it seems, it would be better to remove it at all and add link to “Hazelcast partners” in first sentence for better user experience, or it could be simplified like “See the full list of our partners _link_”

**Comment by Serdaro** [comment]
Fixed with the above commits.
