### ISSUE TITLE
DOCS: IMDG Reference Manual: “Overview: data partitioning” - minor improvements

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/imdg-docs#175]
https://github.com/hazelcast/imdg-docs/blob/master/docs/modules/overview/pages/data-partitioning.adoc

1. They can contain hundreds or thousands of data entries each, depending on the memory capacity of your system - > as for me, it sound ambiguous - number of data entries for fixed capacity of memory depends on entity size . I would propose to redesign to “Number of data entries they can store is limited by physical capacity of your system”
2. The partitions are distributed equally among the members of the cluster. Hazelcast also creates backups of these partitions which are also distributed in the cluster - > Propose to simplify for better user ex: “The partitions and their backups are distributed …”
3. making all members equal and redundant. - > I’m not sure why they are “redundant”, probably, it is better to change this.
4. Hazelcast distributes partitions' primary and backup replicas equally among the members of the cluster. Backup replicas of the partitions are maintained for redundancy. -> this is a duplicate of “The important point here is that Hazelcast equally distributes the partition primaries and their backup replicas among the members.“ And could be removed
5. For ALL members you have in your cluster, the partition ID for a given key is always the same. -> as for me, it is obvious and could be removed
6. And the cluster members to which they belong. -> it is confusing to me. Table could contain link or dares of a member, since member is a separate service instance
7. When you start a member, a partition table is created within it. This table stores the partition IDs and the cluster members to which they belong. The purpose of this table is to make all members (including lite members) in the cluster aware of this information, making sure that each member knows where the data is.-> This is not 100% clear. I think, when member is started, part. Table on master member will be recalculated and updates will be send which is represented in next paragraph. It’s better to reform these.

**Comment by Serdaro** [comment]
1. Agreed
2. Agreed
3. Here, redundant means "having backups"
4. Agreed
5. I'd prefer to leave it as it is just to give the emphasize on the "always"
6. Agreed, will be updated accordingly (IP address of the members)
7. Agreed, will be updated accordingly.

**Comment by Serdaro** [comment]
Fixed with above commits.
