### ISSUE TITLE
DOCS: IMDG Reference Manual: “Rolling Upgrades” - consider adding notes regarding migrations disabling to speed up upgrade

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/imdg-docs#183]
https://docs.hazelcast.com/imdg/5.0-SNAPSHOT/installation/rolling-upgrades.html

Upgrade could be speed up if migrations are disabled, probably, it is good idea to add this information.
Please pay attention it is not common use case, as discussed with Matko.

Please see conversation with Matko:
Vyacheslav Sytnhyk
Are we disabling partition migrations during rolling upgrade?
It could save some time. Not clear from the document

Matko Medenjak  10:43 AM
in the common case, no. Rolling upgrade was meant to be used while the cluster is running other operations where disabling migrations might cause loss of availability.
But you can always avoid migrations by switching to some cluster states which are not ACTIVE (not sure which one would be most appropriate for RU).
generally speaking, customers don’t want any downtime or loss of availability, and disabling migrations goes against this

**Comment by JakeSCahill** [comment]
If this is not a common use case and we aren't sure exactly about how best to do it, I vote for omitting it from the docs.
