### ISSUE TITLE
Docs: Feedback for Partial Network Partitions

### ISSUE THREAD

**Issue by xiaozhiliaoo** [hazelcast/imdg-docs#185]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.2/docs/modules/network-partitioning/pages/partial-network-partitions.adoc)
[N1, N3, N4] and [N2, N3, N4] picture is same as [N1, N2] and [N1, N3, N4]. Is this incorrect？

**Comment by Serdaro** [comment]
Fixed for 5.0-SNAPSHOT and 4.1.x versions.

**Comment by xiaozhiliaoo** [comment]
> Fixed for 5.0-SNAPSHOT and 4.1.x versions.

Thanks.
