### ISSUE TITLE
Docs: Wrong information about HazelcastJsonValue SQL support

### ISSUE THREAD

**Issue by nkonev** [hazelcast/imdg-docs#207]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.2/docs/modules/sql/pages/querying-imap.adoc)

Current link in text
```markdown
For HazelcastJsonValue objects, see the [Querying JSON Strings section](https://docs.hazelcast.com/imdg/4.2/sql/how-distributed-sql-works.html#querying-json-strings)
```
is wrong.

The following is correct https://docs.hazelcast.com/imdg/4.2/query/how-distributed-query-works.html#querying-json-strings

**Comment by nkonev** [comment]
Moreover, currently querying json string is not supported in 4.2, I think it needs to be mentioned.
![Снимок экрана_2021-04-27_07-07-57](https://user-images.githubusercontent.com/3160384/116183862-667d8f80-a727-11eb-8b31-29ce4a013320.png)

Here is reproducer https://github.com/nkonev/hazelcast-example/tree/98208a8ec90d3930c86cfd1bf477d85378b58d48

**Comment by JakeSCahill** [comment]
This was fixed last week, but it appears the change has been overwritten.

This will be fixed when we merge this: https://github.com/hazelcast/hazelcast-docs/pull/156

The change is live here: https://docs.hazelcast.com/imdg/5.0-SNAPSHOT/sql/querying-imap.html#fields

**Comment by nkonev** [comment]
Thank you for response!

**Comment by JakeSCahill** [comment]
This is now fixed with the merge of https://github.com/hazelcast/hazelcast-docs/pull/156
