### ISSUE TITLE
Docs: Feedback for Frequently Asked Questions

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/imdg-docs#212]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/ROOT/pages/faq.adoc)

Suggesting changes to "How do you give support?":

We have two support services: community and commercial support. Community support is provided through our Mail Group, Slack channel and StackOverflow web site. For information on commercial support details, see Hazelcast.com.

And Hazelcast.com should link to: https://hazelcast.com/services/support/

**Comment by sertugkaya** [comment]
Ah, that's what I trying to remember. Thanks

**Comment by Serdaro** [comment]
Closing with above commits.
