### ISSUE TITLE
Docs: Feedback for Maven

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/imdg-docs#222]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/installation/pages/installing-using-maven.adoc)

That section hasn't contain correct dependency definitions for 4.2.(enterprise tab has 4.1.1 dependencies)

**Comment by Serdaro** [comment]
Fixed with the above commit.
