### ISSUE TITLE
Warn that symmetric encryption is deprecated

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/imdg-docs#230]
Page: https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/security/pages/encryption.adoc

There should be a big fat warning that the symmetric encryption has been deprecated since IMDG 4.2. We should check all the places where it's mentioned and put the warning there, like: https://docs.hazelcast.com/imdg/4.2/faq.html#separator question "Is Hazelcast secure?"

**Comment by Serdaro** [comment]
@Holmistr , it is mentioned in the release notes of 4.2 (https://docs.hazelcast.org/docs/rn/#rd-42), but still, let me also add to the intro of this section.

**Comment by Serdaro** [comment]
Fixed with above commits.
