### ISSUE TITLE
Docs: Feedback for Migration Guides

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/imdg-docs#237]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/ROOT/pages/migration-guides.adoc)
Since we have 4.2 migration tool now, below sentence should be corrected:

The tool provides a migration path from a Hazelcast 3.12 cluster to a 4.0/4.1 cluster, not from any previous 3.x versions and not to any future 4.2+ versions.

**Comment by Serdaro** [comment]
Will be changing the whole content (including the title) to update as 3.12 <-> 4.x instead of 3.12 <-> 4.0/4.1

**Comment by Serdaro** [comment]
Fixed with above commits
