### ISSUE TITLE
Docs: Feedback for Java Client. hazelcast.client.invocation.timeout.seconds needs correct default

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/imdg-docs#247]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.1/docs/modules/clients/pages/java.adoc)

The system property `hazelcast.client.invocation.timeout.seconds` has the incorrect default value listed. The actual default is 120 as per [ClientProperty.java](https://github.com/hazelcast/hazelcast/blob/ebfdad1d206ecfcabd2abc6928328ae91da46bc8/hazelcast/src/main/java/com/hazelcast/client/properties/ClientProperty.java#L77).

**Comment by Serdaro** [comment]
Fixed with the above commits.
