### ISSUE TITLE
Docs: Feedback for Diagnostics

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/imdg-docs#253]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/management/pages/diagnostics.adoc)

We are missing descriptions for the following diagnostic plugins and their respective properties:

* InvocationProfilerPlugin: `hazelcast.diagnostics.invocation-profiler.period.seconds` (default 5)
* OperationProfilerPlugin: `hazelcast.diagnostics.operation-profiler.period.seconds` (default 5)

See [InvocationProfilerPlugin.java](https://github.com/hazelcast/hazelcast/blob/7a3f2737aa345f693a59958ea69ed4c2f438b47d/hazelcast/src/main/java/com/hazelcast/internal/diagnostics/InvocationProfilerPlugin.java#L26) and [OperationProfilerPlugin.java](https://github.com/hazelcast/hazelcast/blob/7a3f2737aa345f693a59958ea69ed4c2f438b47d/hazelcast/src/main/java/com/hazelcast/internal/diagnostics/OperationProfilerPlugin.java#L30) for more info.

**Comment by Serdaro** [comment]
Fixed with the above commit.
