### ISSUE TITLE
Docs: Feedback for Quickstart

### ISSUE THREAD

**Issue by ZhaopingJJXie** [hazelcast/imdg-docs#254]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/ROOT/pages/getting-started.adoc)

In the Java Client Application Sample code, 
instead of : 
"import com.hazelcast.core.IMap;",
it should be :
import com.hazelcast.map.IMap;

**Comment by Serdaro** [comment]
Fixed with the above commit.
