### ISSUE TITLE
Docs (v3.12) : Wan replication section have some misinformation

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/imdg-docs#263]
I see there is no `batch-publisher` definition in our 3.12 XSD scheme (http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd), but in our documentation(https://docs.hazelcast.com/imdg/3.12/wan/quick-start.html ), we have the following example ;

```
<wan-replication name="london-wan-rep">
        <batch-publisher>
            <cluster-name>london</cluster-name>
            <target-endpoints>10.3.5.1:5701</target-endpoints>
        </batch-publisher>
    </wan-replication>
```

The issue is not only valid for examples, also some contents have similar issues. It should contain the older documentation's information. https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#defining-wan-replication

**Comment by Serdaro** [comment]
Fixed with the above commits.
