### ISSUE TITLE
Docs: Feedback for Custom Serialization

### ISSUE THREAD

**Issue by cogito-clarus** [hazelcast/imdg-docs#269]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/serialization/pages/custom-serialization.adoc)

the last example shows only:
hazelcast:
  serialization:
    serializers:
      - type-class: Employee
        class-name: EmployeeByteArraySerializer
when i'm sure you mean -type-class: EmployeeSS like in the other examples...

**Comment by Serdaro** [comment]
Yes @cogito-clarus , thanks a lot for reporting. Fixed with the above commit.
