### ISSUE TITLE
Docs: Feedback for C   Client

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/imdg-docs#270]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/clients/pages/cplusplus.adoc)

No more raw pointer API exist.

Change 
`information on setting the client up, installing and compiling it, its serialization support and APIs such as raw pointer and query.`

to

`information on setting the client up, installing and compiling it, its serialization, query support and available APIs.`

**Comment by Serdaro** [comment]
Fixed with the above commit. The changes will be applied to 5.0 docs.
