### ISSUE TITLE
Docs: Feedback for C   Client

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/imdg-docs#271]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/clients/pages/cplusplus.adoc)

Names of the structures and the `setSmartRouting` API changed. Please correct.

**Comment by Serdaro** [comment]
Fixed with the above commit. The changes will be applied to the 5.0 docs.
