### ISSUE TITLE
Docs: Feedback for Configuring for IMap and ICache

### ISSUE THREAD

**Issue by rubenfdez** [hazelcast/imdg-docs#272]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/wan/pages/configuring-for-map-and-cache.adoc)

must be: <merge-policy-class-name> instead of <merge-policy>PassThroughMergePolicy</merge-policy>

**Comment by Serdaro** [comment]
Fixed with the above commit. Also applied to 5.0 BETA-2 and SNAPSHOT documentation.
