### ISSUE TITLE
Docs: Feedback for Using the REST Endpoint Groups

### ISSUE THREAD

**Issue by ufukyilmaz** [hazelcast/imdg-docs#274]
Hi, I have some feedback about [this](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/management/pages/rest-endpoint-groups.adoc) and [that page](https://docs.hazelcast.com/hazelcast/5.0-beta-2/clients/rest.html#using-the-rest-endpoint-groups).
The programmatic configuration example doesn't match with the declarative configuration examples:

```
RestApiConfig restApiConfig = new RestApiConfig()
        .setEnabled(false)
        .enableGroups(RestEndpointGroup.HEALTH_CHECK);
Config config = new Config();
config.getNetworkConfig().setRestApiConfig(restApiConfig);
```

must be replaced with:
```
RestApiConfig restApiConfig = new RestApiConfig()
        .setEnabled(true)
        .disableGroups(RestEndpointGroup.HEALTH_CHECK);
Config config = new Config();
config.getNetworkConfig().setRestApiConfig(restApiConfig);
```
to match.

Also, a similar fix should be made to the `RestServerEndpointConfig` example below.

**Comment by Serdaro** [comment]
Fixed with the above commit. The changes will be applied to 5.0 docs.
