### ISSUE TITLE
Docs: Feedback for Overriding Configuration: Confusion around system property overriding 

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/imdg-docs#275]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.1/docs/modules/configuration/pages/overriding-configuration-settings.adoc)

It seems like some of the details about overriding system properties are incorrect. 

> A new configuration level should be introduced with an underscore (_).

In all examples I've attempted it seems to be that '.' should be used rather than '_' for *system properties*. The following properties (taken from the example) don't work and the member will log warnings:

```
hz.network.port_port-count=100
hz.network.port_port=5701
hz.network.join-auto-detection-enabled=true
```

They work as expected when changed to: 

```
hz.network.port.port-count=100
hz.network.port.port=5701
hz.network.join.auto-detection.enabled=true
```

So, it seems the aforementioned statement and corresponding example needs to be updated to replace the '_' with '.'

**Comment by Serdaro** [comment]
Fixed with the above commit.
