### ISSUE TITLE
Docs: Feedback for Map

### ISSUE THREAD

**Issue by blackthe1st** [hazelcast/imdg-docs#276]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/data-structures/pages/map.adoc)

In Evicting Specific Entries section, it is more like expiration than eviction.

**Comment by Serdaro** [comment]
Thank you @blackthe1st , the whole Map section has been improved for the Hazelcast 5.0 documentation, including topics around the eviction/deleting/expiration of entries. See https://docs.hazelcast.com/hazelcast/5.0/data-structures/updating-map-entries and please feel free to open an issue using this new documentation.
