### ISSUE TITLE
Docs: Feedback for Java Client

### ISSUE THREAD

**Issue by seii** [hazelcast/imdg-docs#285]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/3.12/docs/modules/clients/pages/java.adoc)

Currently the [Configuring Executor Pool Size](https://docs.hazelcast.com/imdg/3.12/clients/java#executorpoolsize) subsection for 3.12 clients is incorrect. It states that the default value for pool size is "5 x core size of the client". However, inspection of [the code](https://github.com/hazelcast/hazelcast/blob/v3.12.12/hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientExecutionServiceImpl.java#L63-L66) indicates that the correct value is "1 x core size of the client".

**Comment by Serdaro** [comment]
Fixed with the above PR
