### ISSUE TITLE
Docs: Feedback for Native Client Security

### ISSUE THREAD

**Issue by seii** [hazelcast/imdg-docs#288]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/security/pages/native-client-security.adoc)

In the "Permissions" section, not all permission are listed. According to the IMDG [version 4.2 XSD file](http://www.hazelcast.com/schema/config/hazelcast-config-4.2.xsd), the following permission items are missing:
- `atomic-reference-permission`
- `durable-executor-service-permission`
- `cardinality-estimator-permission`
- `scheduled-executor-permission`
- `pn-counter-permission`
- `ring-buffer-permission`
- `reliable-topic-permission`

**Comment by Serdaro** [comment]
Already fixed in the Platform docs.
