### ISSUE TITLE
cluster Discovering Members by TCP

### ISSUE THREAD

**Issue by GladiusK** [hazelcast/imdg-docs#291]
SEVERE: [xx.xx.xx.xx]:22002 [dev] [4.0.2] Invalid target for  Registration{filter=com.hazelcast.multimap.impl.MultiMapEventFilter@0, id='5225df72-b666-4aab-b0e2-aeb39bf7216f', serviceName='hz:impl:multiMapService', subscriber=[127.0.0.1]:22002, listener=null}
Nov 26, 2021 2:37:18 PM com.hazelcast.spi.impl.eventservice.EventService

period print above info , if i do something config wrong?

**Comment by Serdaro** [comment]
Hello @GladiusK , for a more effective and fast discussion, you can post the question using the **hazelcast** channel on https://slack.hazelcast.com/
