### ISSUE TITLE
Docs: Hazelcast clients taking long time to get data during node failures

### ISSUE THREAD

**Issue by maheshpvd** [hazelcast/imdg-docs#301]
Hi, I have a question regarding the issue that i'm facing with hazelcast v4.2 during a node failure. During this node failure the client that is trying to fetch data from cache taking long time to get data 20 seconds to 60 seconds. Is this the case during node failure, if yes, can you explain the process that it undergoes in this case. Is there any fix/solution to overcome this case to avoid in future releases. Thanks in advance.

**Comment by Serdaro** [comment]
@maheshpvd , As far as I understand this is not a documentation issue. You can freely ask your question at https://slack.hazelcast.com/ or open an issue at github.com/hazelcast/hazelcast.
