### ISSUE TITLE
Docs: Feedback for Event Journal

### ISSUE THREAD

**Issue by xiaozhiliaoo** [hazelcast/imdg-docs#302]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/3.12/docs/modules/data-structures/pages/event-journal.adoc) . I want to some samples about how to use Event Journal.  Where can i find?

**Comment by Serdaro** [comment]
@xiaozhiliaoo , you can explore https://github.com/hazelcast/hazelcast-code-samples/tree/master/jet/event-journal

**Comment by xiaozhiliaoo** [comment]
> @xiaozhiliaoo , you can explore https://github.com/hazelcast/hazelcast-code-samples/tree/master/jet/event-journal

thank you！
