### ISSUE TITLE
Docs: Feedback for Discovering Members by TCP

### ISSUE THREAD

**Issue by leolux** [hazelcast/imdg-docs#314]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/3.12/docs/modules/clusters/pages/discovering-by-tcp.adoc)

It seems to be missing the member-list tag in the configuration example.

**Comment by Serdaro** [comment]
Thank you @leolux , will also fix in the later IMDG and Platform releases.
