### ISSUE TITLE
Deploying on EC2

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/imdg-docs#42]
This section needs major expansion, right now it is the earliest chapter that people see when researching AWS.  We talk about old vagrant demos with no direct links to them.  We do not mention the discovery plugin at all here.  I would expect this section to at least be a couple of pages long...

https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#deploying-on-amazon-ec2

You can see there are no links which is very annoying, just a general link to code samples.

<img width="791" alt="Screenshot 2019-11-22 16 12 14" src="https://user-images.githubusercontent.com/1588244/69441696-11c03300-0d43-11ea-8c1b-12380b47641f.png">

Also to note, the term "Plugin" will no longer exist, the new .org website has a hub where there is a section for "cloud discovery"

https://hazelcastorg2.wpengine.com/hub/?topic=cloud-discovery&productType=imdg

**Comment by Serdaro** [comment]
https://docs.hazelcast.com/hazelcast/latest/deploy/deploying-on-aws.html
