### ISSUE TITLE
Fix in (log4j2)logging configuration declerative configuration section

### ISSUE THREAD

**Issue by erkangurgen** [hazelcast/imdg-docs#44]
In the log4j2-configuration section the sample declarative configuration is as follows, (https://docs.hazelcast.org/docs/4.1.1/manual/html-single/#example-log4j2-configuration)

```
    <properties>
        <property name="hazelcast.logging.type">log4j2</property>
        <property name="log4j2.configuration">/path/to/properties/log4j2.properties</property>
    </properties>
    ```
    
There is no "log4j2.configuration" Hazelcast property and so this configuration does not set the logging-configuration-file location. 

Setting only <property name="hazelcast.logging.type">log4j2</property> and having the default properties file(log4j2.properties) on the CLASSPATH works.

The other option is the JVM Arguments setting as given in the documentation. 

For declarative configuration we should remove "<property name="log4j2.configuration">/path/to/properties/log4j2.properties</property>" part and add a note describing that the "log4j2.properties" file should be on the CLASSPATH when the declarative configuration is used.

Same applies for all logging options.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/imdg-docs/commit/0af214d3d261232153549903798fa07a040822ab

**Comment by seii** [comment]
This bug appears to still be present in all documentation (old and new designs) except version 4.2-SNAPSHOT.

Examples:
4.1.1 - https://docs.hazelcast.com/imdg/4.1.1/clusters/logging-configuration.html#example-log4j2-configuration
4.0.3 - https://docs.hazelcast.org/docs/4.0.3/manual/html-single/index.html#example-log4j2-configuration
3.12.12 - https://docs.hazelcast.com/imdg/3.12.12/clusters/logging-configuration.html#example-log4j2-configuration

**Comment by Serdaro** [comment]
@seii, we are not able to update the already-published documentation; this update will be present in the future releases starting with 4.1.2 (4.1.z), 4.0.4 (4.0.z), 3.12.13 (3.12.z) and 4.2-BETA-1 (along with 4.2 and 4.2.z)
