### ISSUE TITLE
missing wildcard usage information

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/imdg-docs#57]
https://docs.hazelcast.com/imdg/latest/configuration/using-wildcards.html

Can we add near-cache wildcard usage too, also can we point the hazelcast-client also can use that notation?

eg:

```
<near-cache name="myMap*">
```

**Comment by Serdaro** [comment]
@ilkerkorkut , Actually we talk about those in here: https://docs.hazelcast.com/imdg/latest/performance/near-cache.html#near-cache-configuration-examples.

I am suggesting to change the first paragraph of Using Wildcards section as follows:

```
Hazelcast members and Java clients support wildcard configuration for all distributed data structures that
can be configured using `Config`, that is, for all except `IAtomicLong`,
`IAtomicReference`. Using an asterisk (*) character in the name, different
instances of maps, queues, topics, semaphores, near caches, etc. can be configured by a
single configuration.
```

WDYT?

**Comment by ilkerkorkut** [comment]
@Serdaro it is better 👍 , thanks.
