### ISSUE TITLE
Log4j2 sample configuration only logs to file

### ISSUE THREAD

**Issue by seii** [hazelcast/imdg-docs#67]
**Expected:** As a user of IMDG's [provided Log4j2 configuration](https://docs.hazelcast.com/imdg/latest/clusters/logging-configuration.html#example-log4j2-configuration), I want to have logging print to both the console and a file by default.

**Current:** The provided Log4j2 configuration only prints to a file, leaving the console blank

**Applies to:** All IMDG 3.x and 4.x documentation

Below is an updated logging configuration which makes minimal changes to the example configuration in order to allow both console logging and file logging at the same time. Feel free to use it!

```
rootLogger.level=info
property.filepath=log
property.filename=hazelcast

appenders = console, file

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c\{1}:%L - %m%n

appender.file.type=RollingFile
appender.file.name=RollingFile
appender.file.fileName=${filepath}/${filename}.log
appender.file.filePattern=${filepath}/${filename}-%d{yyyy-MM-dd}-%i.log.gz
appender.file.layout.type=PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c\{1}:%L - %m%n
appender.file.policies.type=Policies
appender.file.policies.time.type=TimeBasedTriggeringPolicy
appender.file.policies.time.interval=1
appender.file.policies.time.modulate=true
appender.file.policies.size.type=SizeBasedTriggeringPolicy
appender.file.policies.size.size=50MB
appender.file.strategy.type=DefaultRolloverStrategy
appender.file.strategy.max=100

rootLogger.appenderRefs= STDOUT
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref=RollingFile

#Hazelcast specific logs.

#log4j.logger.com.hazelcast=debug

#log4j.logger.com.hazelcast.cluster=debug
#log4j.logger.com.hazelcast.partition=debug
#log4j.logger.com.hazelcast.partition.InternalPartitionService=debug
#log4j.logger.com.hazelcast.nio=debug
#log4j.logger.com.hazelcast.hibernate=debug
```

**Comment by Serdaro** [comment]
This has been fixed with the combination of several PRs and commits:

https://github.com/hazelcast/imdg-docs/pull/77,

https://github.com/hazelcast/imdg-docs/pull/69/files#diff-26e6ac5284b37a625debd3216fc4617c62a9e5a2691843102450fc8e50e894cb,

https://github.com/hazelcast/imdg-docs/pull/71/files#diff-26e6ac5284b37a625debd3216fc4617c62a9e5a2691843102450fc8e50e894cb,

https://github.com/hazelcast/imdg-docs/pull/73/files#diff-26e6ac5284b37a625debd3216fc4617c62a9e5a2691843102450fc8e50e894cb
