### ISSUE TITLE
Docs: Community Slack / Resources

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/imdg-docs#88]
Hi. Feedback about [the Resources page](https://github.com/hazelcast/imdg-docs/blob/v4.1.1/docs/modules/overview/pages/resources.adoc):

Hazelcast Community on Slack is missing. Also, I believe it should be more visible than the mail group.
http://hazelcast.slack.com/

**Comment by Serdaro** [comment]
@burakcelebi , just to confirm, the site address should be slack.hazelcast.com, right?

**Comment by Serdaro** [comment]
Fixed with #100 for master and other branches.

**Comment by burakcelebi** [comment]
You are right, thanks :)
