### ISSUE TITLE
Docs: Feedback for Migration Guides

### ISSUE THREAD

**Issue by fghamsary** [hazelcast/imdg-docs#89]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.1.1/docs/modules/ROOT/pages/migration-guides.adoc)

GroupProperty have been renamed to ClusterProperty without any notification and found that in the code.
Just to be more precise I'm talking about `com.hazelcast.spi.properties.GroupProperty`
This has been done from version 3.x to 4.x

**Comment by Serdaro** [comment]
@fghamsary , the change is mentioned in the Breaking Changes section of IMDG 4.0 release notes (https://docs.hazelcast.org/docs/rn/#configuration). But, I think it is good idea to include it in the migration guide too.
Thank you.

**Comment by Serdaro** [comment]
Fixed with #94 .
The same fix will be applied to all 4 version branches.
