### ISSUE TITLE
Docs: Feedback for Java Client - `ClientStateListener` not found by search

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/imdg-docs#97]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/blob/v4.1.1/docs/modules/clients/pages/java.adoc)

The `ClientStateListener` doesn't come up when typed into the search box. If a user finds this class in the codebase but cannot find the documentation for it, this gives the impression that the class isn't meant for public use.

**Comment by sumnerib** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/18333

**Comment by JakeSCahill** [comment]
I think the place for searching API methods should be in the API docs.

It seems like this issue has been fixed in the Javadoc. @sumnerib are you happy for us to close this?

**Comment by sumnerib** [comment]
I can confirm that it's now available in the Javadoc.

> I think the place for searching API methods should be in the API docs.

That makes sense.

Thanks you!
